### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [thbaumann/qgis_db_style_reloader#1]
# Problem

Please populate the metadata.txt 

![reload](https://user-images.githubusercontent.com/2510900/106481138-ccee6b00-64b4-11eb-881e-e7f8b5868f63.png)

**Comment by thbaumann** [comment]
I added the homepage tag so it points to https://github.com/thbaumann/qgis_db_style_reloader/wiki 
Apart from that the plugin has no other homepage.

**Comment by NyakudyaA** [comment]
> I added the homepage tag so it points to https://github.com/thbaumann/qgis_db_style_reloader/wiki
> Apart from that the plugin has no other homepage.

Please also add metadata.txt like other plugins before I can approve

**Comment by thbaumann** [comment]
The metadata.txt is part of the plugin I uploaded at https://plugins.qgis.org.
I think that all required tags are used in the metadata.txt (according to https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/plugins/plugins.html#plugin-metadata-table ).
Can you tell me which part is missing?

**Comment by NyakudyaA** [comment]
> The metadata.txt is part of the plugin I uploaded at https://plugins.qgis.org.
> I think that all required tags are used in the metadata.txt (according to https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/plugins/plugins.html#plugin-metadata-table ).
> Can you tell me which part is missing?

Please compare it with the following https://github.com/kartoza/parcel_plugin/blob/master/metadata.txt. You are missing the `homepage=some_url/`

**Comment by thbaumann** [comment]
ok. Accoording to https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/plugins/plugins.html#plugin-metadata-table
the homepage-tag is not required but I added it at https://github.com/thbaumann/qgis_db_style_reloader/blob/main/metadata.txt#L10 .
Do I have to upload it again at https://plugins.qgis.org/plugins ?
I can't find a menu entry there to re-upload the plugin.

![grafik](https://user-images.githubusercontent.com/20082727/106492993-ded20d00-64b8-11eb-8233-d263cb49e62e.png)

**Comment by NyakudyaA** [comment]
> ok. Accoording to https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/plugins/plugins.html#plugin-metadata-table
> the homepage-tag is not required but I added it at https://github.com/thbaumann/qgis_db_style_reloader/blob/main/metadata.txt#L10 .
> Do I have to upload it again at https://plugins.qgis.org/plugins ?
> I can't find a menu entry there to re-upload the plugin.
> 
> ![grafik](https://user-images.githubusercontent.com/20082727/106492993-ded20d00-64b8-11eb-8233-d263cb49e62e.png)

It is not mandatory but we encourage users to upload it as you can see from the notification I see on the plugin homepage. You have to overwrite the plugin you have uploaded

**Comment by thbaumann** [comment]
Ok. just added also the tracker tag as the plugin uploaded also wanted this tag to be  included.
Uploaded version with these two additional tags in the metadata.txt

**Comment by NyakudyaA** [comment]
> Ok. just added also the tracker tag as the plugin uploader also wanted this tag to be included.
> Uploaded version with these two additional tags in the metadata.txt

Just as a nicer thing to do. Would you mind using a better icon for the plugin. I will approve it now but in the next version it might be useful to have a better icon

**Comment by thbaumann** [comment]
Do you mean https://github.com/thbaumann/qgis_db_style_reloader/blob/main/icons/icon.svg? 
If so what's wrong with this icon?  I thought it would be quite intuitive (style symbol and reload symbol).
